# Generated by Django 3.2.5 on 2021-07-16 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myusers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=myusers.models.image_upload_path, verbose_name='User Image')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date (created)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date (updated)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myusers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
    ]
