# Generated by Django 3.2.5 on 2021-07-19 05:53

from django.db import migrations, models
import django.db.models.deletion
import myusers.models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=myusers.models.image_upload_path, verbose_name='User Image')),
                ('image_type', models.CharField(choices=[('0', 'Additional'), ('1', 'Profile')], max_length=15, verbose_name='Image Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date (created)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date (updated)')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myprofile', to='myusers.userprofile', verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'User Image',
                'verbose_name_plural': 'User Images',
                'db_table': 'user_image',
            },
        ),
    ]
